### PR TITLE
Bump appdata build to focal

### PR DESCRIPTION
**Pull request by danirabbit**

### CODE REVIEW

**Comment by davidmhewitt** [comment]
I _think_ this will need some debian packaging changes too.

Looking at the install files, there's currently wildcards to package everything it finds in the repo, which is currently fine since there's only bionic appdata and icons. But as soon as this is merged, there will be bionic and focal. So I think we'll want to branch this and have a version of the deb packaging that only installs the focal ones and a version that only installs the bionic ones.

**Comment by danirabbit** [comment]
@davidmhewitt I've created a `bionic` branch as a snapshot of the current master. Would it be enough to delete the contents of `pantheon-data` in this branch?

**Comment by davidmhewitt** [comment]
Yup, I suspect that'd do it.

**Comment by danirabbit** [comment]
@davidmhewitt should be done then :)

**Review by davidmhewitt — APPROVED** [review]
Let's give it a go!

**Pull request merged**
